export enum UserStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum DocumentSection {
  FIELD_ITP = 'FIELD_ITP',
  PROCEDURE = 'PROCEDURE',
  WORK_METHOD = 'WORK_METHOD',
}

export enum ReviewStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED_A = 'APPROVED_A',                   // Status A: Approved
  APPROVED_WITH_COMMENTS_B = 'APPROVED_WITH_COMMENTS_B', // Status B: Approved with comments
  REJECTED_C = 'REJECTED_C',                   // Status C: Rejected
  SUPERSEDED = 'SUPERSEDED',                   // Replaced by a newer revision
}

export enum ProjectType {
  TRANSMISSION = 'TRANSMISSION',
  DISTRIBUTION = 'DISTRIBUTION',
  SUBSTATION = 'SUBSTATION',
  GENERATION = 'GENERATION',
  OTHER = 'OTHER',
}

export enum Currency {
  IDR = 'IDR',
  USD = 'USD',
  EUR = 'EUR',
  SGD = 'SGD',
  JPY = 'JPY',
}

export enum ActivityAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REGISTER = 'REGISTER',
  USER_APPROVED = 'USER_APPROVED',
  USER_REJECTED = 'USER_REJECTED',
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  PROJECT_AMENDED = 'PROJECT_AMENDED',
  BOQ_UPLOADED = 'BOQ_UPLOADED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_REVISED = 'DOCUMENT_REVISED',
  REVIEW_SUBMITTED = 'REVIEW_SUBMITTED',
  REVIEW_COMMENTED = 'REVIEW_COMMENTED',
  REVIEW_CHECKED = 'REVIEW_CHECKED',
  REVIEW_APPROVED = 'REVIEW_APPROVED',
  REVIEW_REJECTED = 'REVIEW_REJECTED',
}
